/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Danton e Edianez
 */
public class ViewMalha extends javax.swing.JFrame {

    /**
     * Creates new form ViewMalha
     */
    public ViewMalha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLerArquivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMalha = new javax.swing.JTable();
        btnIniciar = new javax.swing.JButton();
        btnParar = new javax.swing.JButton();
        tfMaxVeiculos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tBtnTipo = new javax.swing.JToggleButton();
        labelTipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLerArquivo.setText("Ler Arquivo");

        tableMalha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableMalha);
        tableMalha.getTableHeader().setUI(null);

        btnIniciar.setText("Iniciar");

        btnParar.setText("Parar");

        jLabel1.setText("Máximo de Veículos:");

        tBtnTipo.setText("Trocar Tipo");

        labelTipo.setText("Semáforo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLerArquivo)
                        .addGap(18, 18, 18)
                        .addComponent(btnIniciar)
                        .addGap(18, 18, 18)
                        .addComponent(btnParar)
                        .addGap(66, 66, 66)
                        .addComponent(tBtnTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMaxVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLerArquivo)
                    .addComponent(btnIniciar)
                    .addComponent(btnParar)
                    .addComponent(tfMaxVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tBtnTipo)
                    .addComponent(labelTipo))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMalha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnLerArquivo;
    private javax.swing.JButton btnParar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JToggleButton tBtnTipo;
    private javax.swing.JTable tableMalha;
    private javax.swing.JTextField tfMaxVeiculos;
    // End of variables declaration//GEN-END:variables


    public void setBtnLerArquivoListener(ActionListener al){
        btnLerArquivo.addActionListener(al);
    }
    
    public void setBtnIniciarListener(ActionListener al){
        btnIniciar.addActionListener(al);
    }
     
    public void setBtnPararListener(ActionListener al){
        btnParar.addActionListener(al);
    }
    
    public void setTfMaxVeiculosListener(DocumentListener al){
        tfMaxVeiculos.getDocument().addDocumentListener(al);
    }
    
    public void setTBtnTipoListener(ActionListener al){
        tBtnTipo.addActionListener(al);
    }
     
     public JLabel getLabelTipo(){
        return labelTipo;
    }
    public JTextField getTfMaxVeiculos(){
        return tfMaxVeiculos;
    }
    
    public JTable getTable(){
        return tableMalha;
    }
}
